// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8YF6a8MP-WPSinSWTFbgAO9dDmoWg87w',
    appId: '1:1049230051071:web:013cfac1a858b528ec6eca',
    messagingSenderId: '1049230051071',
    projectId: 'arcitechassignment',
    authDomain: 'arcitechassignment.firebaseapp.com',
    storageBucket: 'arcitechassignment.appspot.com',
    measurementId: 'G-X76YKK2HHP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrXVqbVcT8fBJ38UvAloA0KTEqWM8Iak8',
    appId: '1:1049230051071:android:aedeef97b3f9188eec6eca',
    messagingSenderId: '1049230051071',
    projectId: 'arcitechassignment',
    storageBucket: 'arcitechassignment.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAu66xk-IvQ9Mvn3eBDs--d7bv0RQ1hWhg',
    appId: '1:1049230051071:ios:63e882bc95d80f5eec6eca',
    messagingSenderId: '1049230051071',
    projectId: 'arcitechassignment',
    storageBucket: 'arcitechassignment.appspot.com',
    iosBundleId: 'com.example.arcitech',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAu66xk-IvQ9Mvn3eBDs--d7bv0RQ1hWhg',
    appId: '1:1049230051071:ios:63e882bc95d80f5eec6eca',
    messagingSenderId: '1049230051071',
    projectId: 'arcitechassignment',
    storageBucket: 'arcitechassignment.appspot.com',
    iosBundleId: 'com.example.arcitech',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8YF6a8MP-WPSinSWTFbgAO9dDmoWg87w',
    appId: '1:1049230051071:web:3a4f649899fc134bec6eca',
    messagingSenderId: '1049230051071',
    projectId: 'arcitechassignment',
    authDomain: 'arcitechassignment.firebaseapp.com',
    storageBucket: 'arcitechassignment.appspot.com',
    measurementId: 'G-LL3W8DNV53',
  );
}
